"use client";

import * as React from "react";
import Link from "next/link";

import { Badge, ScrollRegion } from "@/components/ui/primitives";
import { MetricText } from "@/components/cockpit/metric-text";
import { PageHeader } from "@/components/cockpit/page-header";
import { PanelSection, ReadModelPanel } from "@/components/cockpit/read-model-panel";
import { useScope } from "@/components/shell/use-scope";
import { useMarketRegime } from "@/data/client/hooks";
import type { MarketRegimePayload } from "@/contracts/risk-market-models";
import { decimalSign, humanizeCode } from "@/lib/format";
import { withScope } from "@/lib/scope";
import { cn } from "@/lib/utils";

/**
 * Market & Regime — Area 11.
 *
 * "Show the conditions strategies are operating in."
 *
 *   THE REGIME IS AN INPUT, NOT A CONCLUSION   it is displayed from a recorded, VERSIONED
 *                                              context. **No chart, price series or factor
 *                                              calculation on this page produces it**, and no
 *                                              view recomputes it
 *   THE VIEW SIZES NO EXPOSURE                 sizing stays in the deterministic portfolio and
 *                                              risk logic. Nothing here suggests a position
 *   NO PROFILE IS INVENTED                     the information-set profile is DECLARED. This
 *                                              context is `FORWARD_SYSTEM` — a fixture that
 *                                              knows its own window is **not** point-in-time,
 *                                              and `PUBLIC_PIT` is not reachable from anything
 *                                              this project holds
 */
export default function Page() {
  const { scope } = useScope();
  const operator = scope.mode === "operator";
  const regime = useMarketRegime(scope);

  return (
    <>
      <PageHeader
        title="Market & Regime"
        summary="The versioned regime context the recorded decisions were resolved against, with the information-set profile it was produced under stated on it."
        pageState={regime.data?.payload === undefined ? "PARTIAL" : "COMPLETE"}
      >
        <div className="flex flex-wrap items-center gap-2">
          <Badge tone="neutral">Area 11</Badge>
          <Badge tone="unavailable">No regime engine exists</Badge>
          <Badge tone="unavailable">G1 / G2: OPEN</Badge>
        </div>
      </PageHeader>

      <div className="space-y-4">
        <ReadModelPanel
          title="Recorded regime"
          description="One versioned context. Two screens showing this version are showing one recorded regime, not two derivations of it."
          envelope={regime.data}
          dependency="a regime engine and qualified provider data — neither exists and no provider is selected"
          operator={operator}
          testId="regime-panel"
        >
          {(payload) => <RegimeBody payload={payload} operator={operator} scope={scope} />}
        </ReadModelPanel>
      </div>
    </>
  );
}

function RegimeBody({
  payload,
  operator,
  scope,
}: {
  payload: MarketRegimePayload;
  operator: boolean;
  scope: ReturnType<typeof useScope>["scope"];
}) {
  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-3">
        <Badge tone="accent" data-regime={payload.regime.code}>
          {humanizeCode(payload.regime.code)}
        </Badge>
        <span className="text-label-s text-text-tertiary">
          Context version{" "}
          <span className="font-mono text-text-secondary">{payload.context_version}</span> · as
          of <span className="font-mono text-text-secondary">{payload.as_of}</span>
        </span>
      </div>

      <PanelSection
        title="Information-set profile"
        note="Declared, never inferred, and with no default."
      >
        <div className="flex flex-wrap items-center gap-2">
          <Badge tone="warning" data-profile={payload.information_profile}>
            {humanizeCode(payload.information_profile)}
          </Badge>
        </div>
        <p className="mt-2 max-w-3xl text-label-s leading-relaxed text-text-tertiary">
          <strong className="text-text-secondary">
            This context is FORWARD_SYSTEM, and it must never be read as point-in-time.
          </strong>{" "}
          It is generated by a fixture that knows its whole window, so every score below was
          produced with knowledge a real observer would not have had at that session.{" "}
          <strong className="text-text-secondary">PUBLIC_PIT is not reachable</strong> from
          anything this project holds: no provider is selected, G1 and G2 are open, and the
          candidate provider&rsquo;s price origin is publicly unresolved.
        </p>
      </PanelSection>

      <PanelSection
        title="Components"
        note="Each score is a recorded observation on its own stated scale, so a number is not read as a percentage."
      >
        <ScrollRegion label="Regime components">
          <table className="w-full min-w-[30rem] border-collapse text-label-m" data-testid="regime-components">
            <caption className="sr-only">
              Each recorded regime component, its score and the scale that score is read on.
            </caption>
            <thead>
              <tr className="border-b border-border-subtle text-left text-text-tertiary">
                <th scope="col" className="py-1.5 pr-4 font-medium">
                  Component
                </th>
                <th scope="col" className="py-1.5 pr-4 font-medium">
                  Score
                </th>
                <th scope="col" className="py-1.5 font-medium">
                  Scale
                </th>
              </tr>
            </thead>
            <tbody>
              {payload.components.map((component) => (
                <tr
                  key={component.component.code}
                  className="border-b border-border-subtle last:border-0"
                  data-component={component.component.code}
                >
                  <th
                    scope="row"
                    className="py-1.5 pr-4 text-left font-normal text-text-secondary"
                  >
                    {humanizeCode(component.component.code)}
                  </th>
                  <td className="py-1.5 pr-4">
                    <MetricText metric={component.value} neutral />
                  </td>
                  <td className="py-1.5 text-text-tertiary">
                    {humanizeCode(component.scale.code)}
                  </td>
                </tr>
              ))}
              <tr className="border-t border-border-strong">
                <th scope="row" className="py-1.5 pr-4 text-left font-normal text-text-secondary">
                  Event stress
                </th>
                <td className="py-1.5 pr-4">
                  <MetricText metric={payload.stress} neutral operator={operator} />
                </td>
                <td className="py-1.5 text-text-tertiary">Recorded index</td>
              </tr>
            </tbody>
          </table>
        </ScrollRegion>
      </PanelSection>

      <PanelSection
        title="Sector leadership"
        note="A recorded standing, not a ranking this view computed."
      >
        <ul className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4" data-testid="sector-context">
          {payload.sector_context.map((entry) => {
            const sign =
              typeof entry.value.value === "string" ? decimalSign(entry.value.value) : 0;
            return (
              <li
                key={entry.sector.code}
                className="flex flex-col gap-0.5 rounded-sm border border-border-subtle bg-surface-sunken px-3 py-2"
                data-standing={entry.standing.code}
              >
                <span className="text-label-s text-text-tertiary">
                  {humanizeCode(entry.sector.code)}
                </span>
                <span className="flex items-center gap-2">
                  <span
                    className={cn(
                      "text-label-m font-medium",
                      sign > 0
                        ? "text-positive"
                        : sign < 0
                          ? "text-negative"
                          : "text-text-secondary",
                    )}
                  >
                    <span aria-hidden="true">{sign > 0 ? "▲" : sign < 0 ? "▼" : "■"}</span>{" "}
                    {humanizeCode(entry.standing.code)}
                  </span>
                  <MetricText metric={entry.value} neutral />
                </span>
              </li>
            );
          })}
        </ul>
      </PanelSection>

      <PanelSection
        title="Long and short context"
        note="A recorded stance. It is not an instruction, and nothing on this page sizes an exposure or opens a position."
      >
        <ul className="flex flex-wrap gap-2">
          {payload.side_context.map((entry) => (
            <li key={entry.side}>
              <span className="inline-flex items-center gap-2 rounded-sm border border-border-subtle bg-surface-sunken px-3 py-1.5">
                <Badge tone={entry.side === "LONG" ? "info" : "warning"}>{entry.side}</Badge>
                <span className="text-label-m text-text-secondary">
                  {humanizeCode(entry.stance.code)}
                </span>
              </span>
            </li>
          ))}
        </ul>
      </PanelSection>

      <PanelSection
        title="Regime history"
        note="The recorded stress series, sampled weekly. A gap in it would be PARTIAL and never a zero."
      >
        <StressHistory payload={payload} />
      </PanelSection>

      <p className="max-w-3xl text-label-s leading-relaxed text-text-tertiary">
        Results decomposed by regime are on{" "}
        <Link
          href={withScope("/strategy/performance", scope)}
          className="text-accent underline underline-offset-2"
        >
          Strategy Performance
        </Link>
        , sliced by the same recorded regime this context records — so a trade&rsquo;s regime
        and this page&rsquo;s regime are one fact rather than two derivations.
      </p>
    </div>
  );
}

/**
 * The stress history.
 *
 * A sparkline AND a table, because a chart is never the only access to its own values (U10).
 * The bars are proportional to the recorded score and every value is printed beside them.
 */
function StressHistory({ payload }: { payload: MarketRegimePayload }) {
  const points = payload.history.points;
  const values = points.map((point) =>
    typeof point.v.value === "string" ? Number(point.v.value) : 0,
  );
  const largest = Math.max(1, ...values.map((value) => Math.abs(value)));
  const [tableOpen, setTableOpen] = React.useState(false);

  return (
    <div className="space-y-2">
      <div
        role="img"
        aria-label={`Recorded event-stress index over ${points.length} weekly observations, from ${points[0]?.t ?? "no date"} to ${points[points.length - 1]?.t ?? "no date"}. A table of the same values follows.`}
        className="flex h-16 items-end gap-px overflow-hidden rounded-sm border border-border-subtle bg-surface-sunken p-1"
        data-testid="stress-history"
      >
        {points.map((point, index) => (
          <span
            key={point.t}
            className="min-w-px flex-1 rounded-sm bg-accent"
            style={{ height: `${(Math.abs(values[index]) / largest) * 100}%` }}
            aria-hidden="true"
          />
        ))}
      </div>
      <dl className="flex flex-wrap gap-x-5 gap-y-1 text-label-s text-text-tertiary">
        <div className="flex gap-1.5">
          <dt>Window</dt>
          <dd className="font-mono text-text-secondary">
            {payload.window.from.slice(0, 10)} → {payload.window.to.slice(0, 10)}
          </dd>
        </div>
        <div className="flex gap-1.5">
          <dt>Calendar</dt>
          <dd className="text-text-secondary">{humanizeCode(payload.window.calendar.code)}</dd>
        </div>
        <div className="flex gap-1.5">
          <dt>Granularity</dt>
          <dd className="text-text-secondary">{humanizeCode(payload.history.granularity)}</dd>
        </div>
        <div className="flex gap-1.5">
          <dt>Observations</dt>
          <dd className="font-mono text-text-secondary">
            {payload.history.coverage.present} of {payload.history.coverage.requested}
          </dd>
        </div>
        <div className="flex gap-1.5">
          <dt>Completeness</dt>
          <dd className="text-text-secondary">{humanizeCode(payload.history.completeness)}</dd>
        </div>
      </dl>
      <details
        className="rounded-sm border border-border-subtle bg-surface-sunken"
        onToggle={(event) => setTableOpen(event.currentTarget.open)}
        data-testid="stress-table-disclosure"
      >
        <summary className="cursor-pointer px-3 py-2 text-label-m text-text-secondary">
          Regime history as a table ({points.length} weekly observations)
        </summary>
        {tableOpen && (
          <div className="px-3 pb-3">
            <ScrollRegion label="Regime stress by week" className="max-h-64 overflow-y-auto">
              <table className="w-full min-w-[18rem] border-collapse text-label-m">
                <caption className="sr-only">
                  The recorded event-stress index for each weekly observation.
                </caption>
                <thead>
                  <tr className="border-b border-border-subtle text-left">
                    <th scope="col" className="py-1.5 pr-3 font-medium text-text-tertiary">
                      Week ending
                    </th>
                    <th scope="col" className="py-1.5 font-medium text-text-tertiary">
                      Stress index
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {points.map((point) => (
                    <tr key={point.t} className="border-b border-border-subtle last:border-0">
                      <th
                        scope="row"
                        className="py-1 pr-3 text-left font-mono font-normal text-text-tertiary"
                      >
                        {point.t}
                      </th>
                      <td className="py-1">
                        <MetricText metric={point.v} neutral />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </ScrollRegion>
          </div>
        )}
      </details>
    </div>
  );
}
