import { expect, test, type Page } from "@playwright/test";

/**
 * The committed visual-regression baseline.
 *
 * `ui-ux-specification.md` section 15 asks for "a fixed synthetic fixture set, a fixed
 * viewport list, deterministic rendering, and a stable baseline per route and per state",
 * where "a diff is a review item, not an auto-accept". The fixture set, the viewport list and
 * the per-route, per-state captures already existed as INDEXED REVIEW EVIDENCE in
 * `screenshots-c10/`; what did not exist was the STABLE BASELINE — an image tracked in the
 * repository that a later change is compared against, and that a reviewer can diff.
 *
 * THE BASELINE IS COMMITTED, AND THE REVIEW EVIDENCE IS NOT. They are different artifacts and
 * the distinction is the point. `screenshots/`, `screenshots-c4/` … `screenshots-c10/` are
 * git-ignored capture sets: full-page, many, regenerated on every run, and taken to be looked
 * at. The nine images under `visual-baseline/` are deliberate TEST ASSETS: viewport-sized,
 * few, deterministic, and compared byte-region by byte-region on every run. Nothing in this
 * repository's instructions prohibits a tracked test asset — `.gitattributes` has declared
 * `*.png binary` since before this cycle — and the earlier statement that "a baseline could
 * not be committed" described the screenshot practice rather than a rule.
 *
 * DETERMINISM IS ENGINEERED, NOT HOPED FOR, and it hides nothing.
 *
 *   - the CLOCK IS FROZEN with `page.clock.setFixedTime`. Every figure this Cockpit renders
 *     is derived from the injected clock — the fixture adapter pins its origin to the clock's
 *     first reading and every as-of, age and freshness deadline follows from it — so a frozen
 *     clock makes the whole screen reproducible instead of masking the parts that move.
 *   - REDUCED MOTION is emulated and `animations: "disabled"` is passed, and every chart in
 *     this application already sets `isAnimationActive={false}`.
 *   - the FIXTURES are the repository's own deterministic ones, and the book is generated by
 *     a named linear congruential generator rather than by `Math.random`.
 *   - NOTHING IS MASKED. A mask is a promise not to look, and a baseline with a region nobody
 *     compares is a baseline that cannot catch a regression in it.
 *
 * THE BASELINE IS PLATFORM-SCOPED, and the file name says which platform. Text rasterisation
 * differs between operating systems, so a baseline captured on one is not evidence about
 * another. On a platform with no committed baseline the suite reports the snapshot as missing
 * and FAILS rather than silently accepting whatever it finds; regenerating for that platform
 * is `npx playwright test e2e/c10-visual-regression.spec.ts --update-snapshots`, and the
 * regenerated images are reviewed as a diff exactly as section 15 requires.
 *
 * IT IS REGISTERED IN THE THREE ORIGINAL PROJECTS ONLY — 1440 × 900, 1024 × 768 and
 * 390 × 844 — which is the fixed viewport list this suite has always run, and it is ignored
 * by the three reference-viewport projects so a baseline is not multiplied to eighteen images
 * for coverage the sweep already provides structurally.
 */

/**
 * The instant every capture is taken at.
 *
 * It is inside the fixture set's own window, so the screens render populated rather than
 * expired. Changing it changes every baseline and is a deliberate regeneration.
 */
const FIXED_INSTANT = new Date("2026-09-09T12:00:00.000Z");

/**
 * THE COMPARISON IS EXACT, AND IT IS EXACT BECAUSE THE TOLERANT ONE PROVED INERT.
 *
 * Playwright's default per-pixel `threshold` is 0.2 — a perceptual distance generous enough that
 * a real change goes unnoticed. It was measured rather than assumed: shifting
 * `--color-text-tertiary` from `oklch(0.668 …)` to `oklch(0.640 …)`, a colour change a reader
 * would see, left all nine comparisons GREEN. A baseline that passes through a change it was
 * built to catch is not a baseline, so the tolerance is zero: any differing pixel fails, and the
 * failure is a review item exactly as section 15 requires.
 *
 * Zero tolerance is affordable here only because the rendering is deterministic — frozen clock,
 * no animation, seeded fixtures, one platform per baseline file. Repeated runs on an unchanged
 * tree were confirmed byte-identical before this was tightened, and again afterwards.
 */
const STRICT = { threshold: 0, maxDiffPixels: 0, maxDiffPixelRatio: 0 } as const;

test.use({ reducedMotion: "reduce" });

async function settle(page: Page): Promise<void> {
  await expect(page.getByTestId("freshness-indicator")).toBeVisible();
  await expect(page.getByTestId("context-bar")).toBeVisible();
}

test.describe("the committed visual baseline", () => {
  test("the Executive Overview, populated", async ({ page }) => {
    await page.clock.setFixedTime(FIXED_INSTANT);
    await page.goto("/?scenario=demo&mode=executive");
    await settle(page);
    await expect(page.getByTestId("attention-panel")).toBeVisible();
    await expect(page.getByTestId("what-changed-panel")).toBeVisible();

    await expect(page).toHaveScreenshot("overview-demo-executive.png", {
      animations: "disabled",
      caret: "hide",
      scale: "css",
      ...STRICT,
    });
  });

  test("the Executive Overview, with its producers absent", async ({ page }) => {
    /*
     * THE SECOND STATE OF THE SAME ROUTE. Section 15 asks for a baseline "per route and per
     * state", and the project scenario is the state most of this Cockpit is actually in: the
     * tracked governance facts are real and every operational read model reports that its
     * producer does not exist.
     */
    await page.clock.setFixedTime(FIXED_INSTANT);
    await page.goto("/?scenario=project&mode=executive");
    await settle(page);
    await expect(page.getByTestId("page-provenance-banner")).toContainText("PROJECT READINESS");
    await expect(page.getByTestId("unavailable-body").first()).toBeVisible();

    await expect(page).toHaveScreenshot("overview-project.png", {
      animations: "disabled",
      caret: "hide",
      scale: "css",
      ...STRICT,
    });
  });

  test("the eleven availability states", async ({ page }) => {
    /*
     * THE STATE REFERENCE SCREEN, which renders every availability state at once. U4 and U5
     * require that they render distinctly and that none reads as zero or as healthy; a
     * baseline over this screen is what would catch a later change collapsing two of them
     * into one appearance without changing a single assertion.
     */
    await page.clock.setFixedTime(FIXED_INSTANT);
    await page.goto("/foundation/states?scenario=demo");
    await settle(page);
    await expect(page.getByTestId("freshness-demo")).toBeVisible();

    await expect(page).toHaveScreenshot("availability-states.png", {
      animations: "disabled",
      caret: "hide",
      scale: "css",
      ...STRICT,
    });
  });
});
