/**
 * `MarketRegime`, from the demonstration book's versioned regime context.
 *
 * **THE REGIME IS AN INPUT, NOT A CONCLUSION.** It is displayed from a recorded, versioned
 * context and **is never recomputed by a view** — no chart, no price series and no factor
 * calculation here produces it. **The view sizes no exposure.**
 *
 * **THE INFORMATION-SET PROFILE IS DECLARED, AND IT IS THE WEAKEST ONE.** This context is
 * generated by a fixture that knows its whole window, so it is `FORWARD_SYSTEM` and **must
 * never be read as point-in-time**. `PUBLIC_PIT` is not reachable from anything this project
 * holds: no provider is selected, **G1 and G2 are OPEN**, and Sharadar price origin stays
 * `PUBLICLY_UNRESOLVED` (Q7). **No default profile is invented.**
 */
import type { MarketRegimePayload } from "@/contracts/risk-market-models";
import type { SeriesPoint } from "@/contracts/values";

import { SECURITIES, centsToDecimal } from "./book";
import {
  CALENDAR,
  demoReason,
  scaled,
  sessionInstant,
  windowOf,
} from "./common";
import { granularitySamples } from "./equity";
import { regimeAtSession, volatilityRegimeAtSession } from "./strategy";

/** The recorded context identity. Two screens showing this are showing one recorded regime. */
const CONTEXT_VERSION = "regime-context-demo-v1";

/** The components Area 11 names, each a recorded score on its own stated scale. */
const COMPONENTS = [
  { code: "TREND", scale: "MINUS_ONE_TO_ONE", value: 42 },
  { code: "BREADTH", scale: "MINUS_ONE_TO_ONE", value: 18 },
  { code: "VOLATILITY", scale: "MINUS_ONE_TO_ONE", value: -26 },
  { code: "MOMENTUM_CRASH_STATE", scale: "MINUS_ONE_TO_ONE", value: -12 },
  { code: "FACTOR_REGIME", scale: "MINUS_ONE_TO_ONE", value: 31 },
  { code: "EVENT_STRESS", scale: "MINUS_ONE_TO_ONE", value: -8 },
] as const;

/** Sector leadership, as a recorded standing rather than a ranking a view computed. */
const SECTOR_STANDING: Readonly<Record<string, { standing: string; value: number }>> = {
  MATERIALS: { standing: "LEADING", value: 58 },
  HEALTH_CARE: { standing: "LAGGING", value: -34 },
  INDUSTRIALS: { standing: "LEADING", value: 41 },
  INFORMATION_TECHNOLOGY: { standing: "NEUTRAL", value: 6 },
  CONSUMER_DISCRETIONARY: { standing: "LAGGING", value: -47 },
  ENERGY: { standing: "LEADING", value: 63 },
  FINANCIALS: { standing: "NEUTRAL", value: 11 },
  UTILITIES: { standing: "LAGGING", value: -22 },
};

/**
 * The stress history the context recorded, sampled weekly.
 *
 * It is a `Series`, so it carries its calendar, its timezone, its coverage and its
 * completeness like every other series — a gap in it would be `PARTIAL` and never a zero.
 */
function stressHistory(days: readonly string[], asOf: string) {
  const samples = granularitySamples(days, "WEEKLY");
  const points: SeriesPoint[] = samples.map((sessionIndex) => {
    /*
     * A recorded score, derived from the same fixed regime partition the ledger's slices are
     * read against — so the regime a trade was entered in and the regime the history shows
     * for that week are the same recorded fact.
     */
    const regime = regimeAtSession(sessionIndex);
    const base =
      regime === "HIGH_VOLATILITY_STRESS" ? 68 : regime === "RANGE_BOUND" ? 34 : 21;
    const wobble = ((sessionIndex * 37) % 13) - 6;
    return {
      t: days[sessionIndex],
      v: scaled("market.stress", "DIMENSIONLESS", base + wobble, asOf),
    };
  });
  return {
    points,
    granularity: "WEEKLY" as const,
    calendar: CALENDAR,
    timezone: "UTC" as const,
    coverage: { present: points.length, requested: points.length },
    completeness: "COMPLETE" as const,
  };
}

export function syntheticMarketRegime(
  asOf: string,
  days: readonly string[],
): MarketRegimePayload {
  const lastSession = days.length - 1;
  const snapshotAt = sessionInstant(days[lastSession]);
  const stressPoints = stressHistory(days, asOf);
  const currentStress = stressPoints.points[stressPoints.points.length - 1];

  return {
    context_version: CONTEXT_VERSION,
    as_of: snapshotAt,
    regime: demoReason(regimeAtSession(lastSession)),
    components: [
      ...COMPONENTS.map((component) => ({
        component: demoReason(component.code),
        value: scaled("market.component_score", "DIMENSIONLESS", component.value, snapshotAt),
        scale: demoReason(component.scale),
      })),
      {
        component: demoReason("VOLATILITY_REGIME"),
        value: scaled(
          "market.component_score",
          "DIMENSIONLESS",
          volatilityRegimeAtSession(lastSession) === "ELEVATED_VOLATILITY" ? 74 : 22,
          snapshotAt,
        ),
        scale: demoReason("ZERO_TO_ONE_HUNDRED"),
      },
    ],
    stress: scaled(
      "market.stress",
      "DIMENSIONLESS",
      Number(String(currentStress.v.value).replace(".", "")),
      snapshotAt,
    ),
    history: stressPoints,
    /** DECLARED. A fixture that knows its own window is not point-in-time. */
    information_profile: "FORWARD_SYSTEM",
    sector_context: [...new Set(SECURITIES.map((security) => security.sector))].map(
      (sector) => {
        const standing = SECTOR_STANDING[sector] ?? { standing: "NEUTRAL", value: 0 };
        return {
          sector: demoReason(sector),
          standing: demoReason(standing.standing),
          value: scaled(
            "market.component_score",
            "DIMENSIONLESS",
            standing.value,
            snapshotAt,
          ),
        };
      },
    ),
    /**
     * The long and short context the record carries.
     *
     * **It is a recorded stance, not an instruction.** Nothing on this screen sizes an
     * exposure, opens a position or authorizes one.
     */
    side_context: [
      { side: "LONG", stance: demoReason("LONG_CONTEXT_RECORDED_AS_CONSTRUCTIVE") },
      { side: "SHORT", stance: demoReason("SHORT_CONTEXT_RECORDED_AS_SELECTIVE") },
    ],
    window: windowOf(days),
  };
}

export { centsToDecimal };
